# Generated by Django 3.1.7 on 2021-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210614_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(max_length=100000),
        ),
    ]
