# Generated by Django 3.1.7 on 2021-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210614_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icn', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(max_length=10000000),
        ),
    ]
