# Generated by Django 3.1.7 on 2021-06-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
